import { Badge, Button, Center, Menu, Skeleton, Table, Text } from "@mantine/core";
import { IconDots, IconEdit, IconEye, IconTrash } from "@tabler/icons-react";
import { Link } from "react-router-dom";
import type { ServicioRecurrente } from "../../api/serviciosRecurrentes";
import ServicioRecurrenteStatusBadge from "./ServicioRecurrenteStatusBadge";

interface Props { servicios: ServicioRecurrente[]; clientes: Record<string, string>; productos: Record<string, string>; loading: boolean; onEdit: (item: ServicioRecurrente) => void; onDelete: (item: ServicioRecurrente) => void }

function formatDate(value: string) { return new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }
function renewalState(value: string) { const days = Math.ceil((new Date(`${value}T00:00:00`).getTime() - new Date().setHours(0, 0, 0, 0)) / 86400000); return days < 0 ? { label: "Vencido", color: "red" } : days <= 30 ? { label: `${days} días`, color: "yellow" } : { label: "", color: "gray" }; }
function Actions({ item, onEdit, onDelete }: { item: ServicioRecurrente; onEdit: (item: ServicioRecurrente) => void; onDelete: (item: ServicioRecurrente) => void }) { return <Menu shadow="sm" position="bottom-end" withinPortal><Menu.Target><Button variant="subtle" color="gray" size="compact-sm" aria-label={`Acciones de ${item.descripcion}`} px={6}><IconDots size={18} /></Button></Menu.Target><Menu.Dropdown><Menu.Item component={Link} to={`/recurrentes/${item.id}`} leftSection={<IconEye size={16} />}>Ver servicio</Menu.Item><Menu.Item onClick={() => onEdit(item)} leftSection={<IconEdit size={16} />}>Editar</Menu.Item><Menu.Divider /><Menu.Item color="red" onClick={() => onDelete(item)} leftSection={<IconTrash size={16} />}>Eliminar</Menu.Item></Menu.Dropdown></Menu>; }
function SkeletonRows() { return <>{Array.from({ length: 5 }, (_, index) => <Table.Tr key={index}>{Array.from({ length: 7 }, (_, cell) => <Table.Td key={cell}><Skeleton height={16} width={cell === 1 ? "70%" : 90} /></Table.Td>)}</Table.Tr>)}</>; }

export default function ServiciosRecurrentesTable({ servicios, clientes, productos, loading, onEdit, onDelete }: Props) { return <div className="recurring-table-shell"><Table className="recurring-table" verticalSpacing="sm"><Table.Thead><Table.Tr><Table.Th>Cliente</Table.Th><Table.Th>Servicio</Table.Th><Table.Th>Periodicidad</Table.Th><Table.Th>Precio</Table.Th><Table.Th>Próxima renovación</Table.Th><Table.Th>Estado</Table.Th><Table.Th>Acciones</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{loading ? <SkeletonRows /> : servicios.map((item) => { const renewal = renewalState(item.proximaRenovacion); return <Table.Tr key={item.id}><Table.Td><Text component={Link} to={`/clientes/${item.clienteId}`} className="recurring-link" fw={600}>{clientes[item.clienteId] || "—"}</Text></Table.Td><Table.Td><Text component={Link} to={`/recurrentes/${item.id}`} className="recurring-link" fw={650} truncate>{item.descripcion}</Text>{item.productoId && <Text size="xs" c="dimmed">{productos[item.productoId] || "—"}</Text>}</Table.Td><Table.Td>{item.periodicidad}</Table.Td><Table.Td>{Number(item.precio).toFixed(2)} €</Table.Td><Table.Td><Text size="sm">{formatDate(item.proximaRenovacion)}</Text>{renewal.label && <Badge color={renewal.color} variant="light" mt={4}>{renewal.label}</Badge>}</Table.Td><Table.Td><ServicioRecurrenteStatusBadge status={item.estado} /></Table.Td><Table.Td><Actions item={item} onEdit={onEdit} onDelete={onDelete} /></Table.Td></Table.Tr>; })}</Table.Tbody></Table>{!loading && !servicios.length && <Center py="xl"><Text size="sm" c="dimmed">No hay servicios que coincidan con los filtros.</Text></Center>}</div>; }
