import { Button, Group, Menu, Select, Text, TextInput } from "@mantine/core";
import { IconAdjustmentsHorizontal, IconPlus, IconSearch } from "@tabler/icons-react";
import type { Periodicidad, ServicioRecurrenteEstado } from "../../api/serviciosRecurrentes";
import { labels } from "./ServicioRecurrenteStatusBadge";

interface Props { search: string; status: "todos" | ServicioRecurrenteEstado; periodicidad: "todas" | Periodicidad; count: number; onSearchChange: (value: string) => void; onStatusChange: (value: "todos" | ServicioRecurrenteEstado) => void; onPeriodicityChange: (value: "todas" | Periodicidad) => void; onCreate: () => void }
const periods: { value: Periodicidad; label: string }[] = [{ value: "mensual", label: "Mensual" }, { value: "trimestral", label: "Trimestral" }, { value: "anual", label: "Anual" }];

export default function ServiciosRecurrentesToolbar({ search, status, periodicidad, count, onSearchChange, onStatusChange, onPeriodicityChange, onCreate }: Props) {
  return <Group justify="space-between" align="center" gap="md" wrap="wrap" className="clients-toolbar"><Group gap="sm" wrap="wrap"><TextInput aria-label="Buscar servicios recurrentes" placeholder="Buscar servicios..." value={search} onChange={(event) => onSearchChange(event.currentTarget.value)} leftSection={<IconSearch size={16} />} className="clients-search" /><Menu shadow="sm" position="bottom-start" withinPortal><Menu.Target><Button variant="light" leftSection={<IconAdjustmentsHorizontal size={16} />}>Estado{status !== "todos" ? `: ${labels[status]}` : ""}</Button></Menu.Target><Menu.Dropdown><Menu.Label>Filtrar por estado</Menu.Label><Menu.Item onClick={() => onStatusChange("todos")}>Todos</Menu.Item>{(Object.keys(labels) as ServicioRecurrenteEstado[]).map((value) => <Menu.Item key={value} onClick={() => onStatusChange(value)}>{labels[value]}</Menu.Item>)}</Menu.Dropdown></Menu><Select aria-label="Filtrar por periodicidad" placeholder="Periodicidad" clearable data={periods} value={periodicidad === "todas" ? null : periodicidad} onChange={(value) => onPeriodicityChange((value as Periodicidad | null) ?? "todas")} className="recurring-period-filter" /></Group><Group gap="md" ml="auto"><Text size="sm" c="dimmed">{count} {count === 1 ? "servicio" : "servicios"}</Text><Button leftSection={<IconPlus size={16} />} onClick={onCreate}>Nuevo servicio</Button></Group></Group>;
}
