import { Button, Center, Menu, Skeleton, Table, Text } from "@mantine/core";
import { IconDots, IconEdit, IconEye, IconTrash } from "@tabler/icons-react";
import { Link } from "react-router-dom";
import type { Tarea } from "../../api/tareas";
import TareaStatusBadge from "./TareaStatusBadge";

interface Props { tareas: Tarea[]; proyectos: Record<string, { nombre: string; cliente: string }>; loading: boolean; onEdit: (tarea: Tarea) => void; onDelete: (tarea: Tarea) => void }

function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("es-ES", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—"; }
function Actions({ tarea, onEdit, onDelete }: { tarea: Tarea; onEdit: (tarea: Tarea) => void; onDelete: (tarea: Tarea) => void }) { return <Menu shadow="sm" position="bottom-end" withinPortal><Menu.Target><Button variant="subtle" color="gray" size="compact-sm" aria-label={`Acciones de ${tarea.titulo}`} px={6}><IconDots size={18} /></Button></Menu.Target><Menu.Dropdown><Menu.Item component={Link} to={`/tareas/${tarea.id}`} leftSection={<IconEye size={16} />}>Ver tarea</Menu.Item><Menu.Item onClick={() => onEdit(tarea)} leftSection={<IconEdit size={16} />}>Editar</Menu.Item><Menu.Divider /><Menu.Item color="red" onClick={() => onDelete(tarea)} leftSection={<IconTrash size={16} />}>Eliminar</Menu.Item></Menu.Dropdown></Menu>; }
function SkeletonRows() { return <>{Array.from({ length: 5 }, (_, index) => <Table.Tr key={index}>{Array.from({ length: 6 }, (_, cell) => <Table.Td key={cell}><Skeleton height={16} width={cell === 0 ? "70%" : 90} /></Table.Td>)}</Table.Tr>)}</>; }

export default function TareasTable({ tareas, proyectos, loading, onEdit, onDelete }: Props) { return <div className="tasks-table-shell"><Table className="tasks-table" verticalSpacing="sm"><Table.Thead><Table.Tr><Table.Th>Tarea</Table.Th><Table.Th>Proyecto</Table.Th><Table.Th>Cliente</Table.Th><Table.Th>Estado</Table.Th><Table.Th>Fecha de creación</Table.Th><Table.Th>Acciones</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{loading ? <SkeletonRows /> : tareas.map((tarea) => { const relation = proyectos[tarea.proyectoId]; return <Table.Tr key={tarea.id}><Table.Td><Text component={Link} to={`/tareas/${tarea.id}`} fw={650} className="task-name-link">{tarea.titulo}</Text></Table.Td><Table.Td><Text component={Link} to={`/proyectos/${tarea.proyectoId}`} className="task-related-link">{relation?.nombre || "—"}</Text></Table.Td><Table.Td>{relation?.cliente || "—"}</Table.Td><Table.Td><TareaStatusBadge status={tarea.estado} /></Table.Td><Table.Td><Text size="sm" c="dimmed">{formatDate(tarea.createdAt)}</Text></Table.Td><Table.Td><Actions tarea={tarea} onEdit={onEdit} onDelete={onDelete} /></Table.Td></Table.Tr>; })}</Table.Tbody></Table>{!loading && !tareas.length && <Center py="xl"><Text size="sm" c="dimmed">No hay tareas que coincidan con los filtros.</Text></Center>}</div>; }
